"use client";
import { useActionState, useState } from "react";
import { login, type LoginState } from "./actions";
import type { TeacherQa } from "./server-data";
const initialState: LoginState = { ok: false };
export default function Portal({ questions }: { questions: TeacherQa[] }) {
  const [state, action, pending] = useActionState(login, initialState); const [qaStage,setQaStage]=useState(1); const [attendanceStage,setAttendanceStage]=useState(1);
  const visibleQa=questions.filter(q=>q.stage===qaStage); const visibleRecords=state.data?.records.filter(r=>r.stage===attendanceStage)??[];
  return <main><header className="hero"><nav><a className="brand" href="#top"><span>AI</span> 青年實戰養成班</a><div><a href="#attendance">出席查詢</a><a href="#qa">課堂 QA</a></div></nav><div className="hero-copy" id="top"><p className="eyebrow">CLASS 01 · 學習入口</p><h1>掌握自己的學習進度，<br/><em>每一堂都算數。</em></h1><p>登入查看個人出席紀錄，或直接瀏覽教師對課堂問題的完整回覆。</p><div className="hero-actions"><a className="button primary" href="#attendance">查詢我的出席</a><a className="button ghost" href="#qa">瀏覽課堂 QA</a></div></div><div className="hero-stat"><strong>120</strong><span>課程總時數</span></div></header>
  <section id="attendance" className="section attendance"><Heading eyebrow="MY ATTENDANCE" title="出席紀錄查詢">帳號為學生編號，初始密碼為身分證後三碼。查詢結果僅顯示您本人的資料。</Heading>
  {!state.ok?<form action={action} className="login-card"><div className="login-intro"><span className="step">01</span><h3>登入查詢</h3><p>請輸入您的個人驗證資料</p></div><label>學生編號<input name="studentId" inputMode="numeric" autoComplete="username" placeholder="例如：07" required/></label><label>身分證後三碼<input name="password" type="password" inputMode="numeric" maxLength={3} pattern="[0-9]{3}" autoComplete="current-password" placeholder="•••" required/></label><input className="trap" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/>{state.message&&<p className="error" role="alert">{state.message}</p>}<button disabled={pending}>{pending?"查詢中…":"查看我的出席紀錄 →"}</button><small>為保障個資，請勿在共用裝置保存密碼。</small></form>
  :<div className="result-card"><div className="result-top"><div><p className="eyebrow">WELCOME BACK</p><h3>{state.data?.name} 同學</h3><p>以下為目前已登錄的缺席紀錄</p></div><div className="rate"><span>總出席率</span><strong>{state.data?.attendanceRate.toFixed(1)}<i>%</i></strong><small>已缺席 {state.data?.absentHours} 小時 / 共 120 小時</small></div></div><StageTabs active={attendanceStage} onChange={setAttendanceStage}/>{visibleRecords.length?<div className="table-wrap"><table><thead><tr><th>請假日期</th><th>時間</th><th>請假事由</th><th>狀態</th></tr></thead><tbody>{visibleRecords.map((r,i)=><tr key={i}><td>{r.date}</td><td>{r.time} <small>({r.hours} 小時)</small></td><td>{r.reason}</td><td><span className={`badge ${r.status}`}>{r.status}</span></td></tr>)}</tbody></table></div>:<Empty title="本階段沒有缺席紀錄">太棒了，請繼續保持！</Empty>}<p className="formula">出席率依「（120 小時－缺席時數）÷ 120 小時 × 100%」計算。</p></div>}</section>
  <section id="qa" className="section qa"><Heading eyebrow="CLASSROOM Q&A" title="教師課堂問題回覆">不須登入即可瀏覽。整理課堂上同學提出的問題，以及教師的重點回應。</Heading><StageTabs active={qaStage} onChange={setQaStage}/><div className="qa-list">{visibleQa.length?visibleQa.map((q,i)=><article key={i} className="qa-card"><div className="qa-meta"><span>{q.course}</span><span>{q.date}</span></div><div className="question"><b>Q</b><h3>{q.question}</h3></div><div className="answer"><b>A</b><div><p>{q.answer}</p><small>— {q.teacher} 老師</small></div></div></article>):<Empty title="第二階段 QA 尚未公布">教師回覆更新後將顯示於此。</Empty>}</div></section><footer><span>青年 AI 實戰養成班 · 1 班</span><span>若出席資料有誤，請聯繫課程承辦人員。</span></footer></main>;
}
function Heading({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><p>{children}</p></div>}
function StageTabs({active,onChange}:{active:number;onChange:(n:number)=>void}){return <div className="tabs" aria-label="課程階段">{[1,2].map(n=><button key={n} className={active===n?"active":""} onClick={()=>onChange(n)} type="button"><span>階段 0{n}</span><small>{n===1?"基礎實作":"進階應用"}</small></button>)}</div>}
function Empty({title,children}:{title:string;children:React.ReactNode}){return <div className="empty"><strong>{title}</strong><span>{children}</span></div>}
